# Common vars
availability_zone: melbourne-qh2-uom


# Security group
security_groups:
  - name: jimmy_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: jimmy_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: jimmy_couchdb5984
    description: "open the port for couchdb"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: jimmy_couchdb4369
    description: "open the port for couchdb"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0
  - name: jimmy_couchdb9100-9200
    description: "open the port for couchdb"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_ip_prefix: 0.0.0.0/0
  - name: backend port 
    description: open this port for backend
    protocol: tcp
    port_range_min: 8080
    port_range_max: 8080
    remote_ip_prefix: 0.0.0.0/0


# Volume
volumes:
  - vol_name: vol-1
    vol_size: 70
    device: "/dev/vdb"
    mountpoint: /data
  - vol_name: vol-2
    vol_size: 70
    device: "/dev/vdb"
    mountpoint: /data
  - vol_name: vol-3
    vol_size: 70
    device: "/dev/vdb"
    mountpoint: /data
  - vol_name: vol-4
    vol_size: 40
    device: "/dev/vdb"
    mountpoint: /data

# Instance
instances: 
  - name: instance1
    volumes: ['vol-1']
  - name: instance2
    volumes: ['vol-2']
  - name: instance3
    volumes: ['vol-3']
  - name: instance4
    volumes: ['vol-4']

# instance_image: 45225edb-66d8-4fd0-bf41-132a31a18166
instance_image: 41a92d84-b2d4-4529-b729-1fb92153f0f0
instance_key_name: JimmyLsc
instance_flavor: uom.mse.2c9g

workplace_path: "/Users/jimmylsc/Desktop/ansible/instance"
remote_home: "/home/ubuntu"
